name: CI
on:
  pull_request:
  push:
  schedule:
    - cron:  '0 12 * * *'
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v8

      - name: Build all examples
        run: |
          nix-build -A examplesBuilds

